- name: Setup 'the cloud' from local machine
  hosts: localhost
  vars_files:
    - vars/cloud.yml
  vars:
    firewall_name: "holy-firewall"
    server_name: "holy-server"
  pre_tasks:
    - name: Update cache
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
  tasks:
    - include_tasks: tasks/hcloud.yml