- name: Install hcloud on macOS via Homebrew
  community.general.homebrew:
    name: hcloud
    state: present
- name: Ensure firewall exists (allow SSH/HTTP/HTTPS for IPv4+IPv6)
  hetzner.hcloud.hcloud_firewall:
    api_token: "{{ hcloud_token }}"
    name: "{{ firewall_name }}"
    rules:
      - direction: in
        protocol: tcp
        port: "22"
        source_ips: ["0.0.0.0/0", "::/0"]
      - direction: in
        protocol: tcp
        port: "80"
        source_ips: ["0.0.0.0/0", "::/0"]
      - direction: in
        protocol: tcp
        port: "443"
        source_ips: ["0.0.0.0/0", "::/0"]
    state: present
- name: Look up server by name
  hetzner.hcloud.server_info:
    api_token: "{{ hcloud_token }}"
    name: "{{ server_name }}"
  register: server_info
- name: Attach firewall to server
  hetzner.hcloud.firewall_resource:
    api_token: "{{ hcloud_token }}"
    firewall: "{{ firewall_name }}"
    servers:
      - "{{ server_info.hcloud_server_info[0].id }}"
    state: present
