- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_ssh_folder }}"
    mode: 0700
    state: directory
  tags:
    - local
    - ssh
# ssh keys for local machine
- name: Install ssh key
  copy:
    src: "{{ ssh_folder }}/id_rsa_local.pub"
    dest: "{{ dest_ssh_folder }}/id_rsa_local.pub"
    mode: 0600
  tags:
    - local
    - ssh
